name: CodeAnalysisCheck

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches:
      - main

jobs:
  codeAnalysisCheck:
    name: Code analysis check
    runs-on: macos-12

    steps:
      - name: Checking out branch
        uses: actions/checkout@v3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run Detekt
        run: ./gradlew detekt --gradle-user-home .gradle

      - name: Run Ktlint
        run: ./gradlew ktlintCheck --gradle-user-home .gradle

      - name: Run konsist tests
        run: ./gradlew :konsistTest:jvmTest --gradle-user-home .gradle